/**
 *
 *  RestfulNewsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulNewsCtrlBase.h"

#include "News.h"
using namespace drogon;

using namespace drogon_model::openproject6;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the news table.
 */

class RestfulNewsCtrl: public drogon::HttpController<RestfulNewsCtrl>, public RestfulNewsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulNewsCtrl::getOne,"/news/{1}",Get,Options);
    ADD_METHOD_TO(RestfulNewsCtrl::updateOne,"/news/{1}",Put,Options);
    ADD_METHOD_TO(RestfulNewsCtrl::deleteOne,"/news/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulNewsCtrl::get,"/news",Get,Options);
    ADD_METHOD_TO(RestfulNewsCtrl::create,"/news",Post,Options);
    //ADD_METHOD_TO(RestfulNewsCtrl::update,"/news",Put,Options);
    METHOD_LIST_END
    
    /**
     * Uncomment the following methods to customize for business logic.
     */
     /*
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                News::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   News::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   News::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback);
    */
};
