/**
 *
 *  RestfulVersionsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulVersionsCtrl.h"
#include <string>




/**
* Uncomment the following methods to customize for business logic.
*/
/*
void RestfulVersionsCtrl::getOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Versions::PrimaryKeyType &&id)
{
    RestfulVersionsCtrlBase::getOne(req, callback, id);
}


void RestfulVersionsCtrl::updateOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Versions::PrimaryKeyType &&id)
{
    RestfulVersionsCtrlBase::updateOne(req, callback, id);
}


void RestfulVersionsCtrl::deleteOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Versions::PrimaryKeyType &&id)
{
    RestfulVersionsCtrlBase::deleteOne(req, callback, id);
}

void RestfulVersionsCtrl::get(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulVersionsCtrlBase::get(req, callback);
}

void RestfulVersionsCtrl::create(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulVersionsCtrlBase::create(req, callback);
}

*/
