/**
 *
 *  RestfulRecaptchaEntriesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulRecaptchaEntriesCtrl.h"
#include <string>




/**
* Uncomment the following methods to customize for business logic.
*/
/*
void RestfulRecaptchaEntriesCtrl::getOne(const HttpRequestPtr &req,
                                         std::function<void(const HttpResponsePtr &)> &&callback,
                                         RecaptchaEntries::PrimaryKeyType &&id)
{
    RestfulRecaptchaEntriesCtrlBase::getOne(req, callback, id);
}


void RestfulRecaptchaEntriesCtrl::updateOne(const HttpRequestPtr &req,
                                            std::function<void(const HttpResponsePtr &)> &&callback,
                                            RecaptchaEntries::PrimaryKeyType &&id)
{
    RestfulRecaptchaEntriesCtrlBase::updateOne(req, callback, id);
}


void RestfulRecaptchaEntriesCtrl::deleteOne(const HttpRequestPtr &req,
                                            std::function<void(const HttpResponsePtr &)> &&callback,
                                            RecaptchaEntries::PrimaryKeyType &&id)
{
    RestfulRecaptchaEntriesCtrlBase::deleteOne(req, callback, id);
}

void RestfulRecaptchaEntriesCtrl::get(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulRecaptchaEntriesCtrlBase::get(req, callback);
}

void RestfulRecaptchaEntriesCtrl::create(const HttpRequestPtr &req,
                                         std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulRecaptchaEntriesCtrlBase::create(req, callback);
}

*/
