/**
 *
 *  RestfulWebhooksWebhooksCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulWebhooksWebhooksCtrl.h"
#include <string>




/**
* Uncomment the following methods to customize for business logic.
*/
/*
void RestfulWebhooksWebhooksCtrl::getOne(const HttpRequestPtr &req,
                                         std::function<void(const HttpResponsePtr &)> &&callback,
                                         WebhooksWebhooks::PrimaryKeyType &&id)
{
    RestfulWebhooksWebhooksCtrlBase::getOne(req, callback, id);
}


void RestfulWebhooksWebhooksCtrl::updateOne(const HttpRequestPtr &req,
                                            std::function<void(const HttpResponsePtr &)> &&callback,
                                            WebhooksWebhooks::PrimaryKeyType &&id)
{
    RestfulWebhooksWebhooksCtrlBase::updateOne(req, callback, id);
}


void RestfulWebhooksWebhooksCtrl::deleteOne(const HttpRequestPtr &req,
                                            std::function<void(const HttpResponsePtr &)> &&callback,
                                            WebhooksWebhooks::PrimaryKeyType &&id)
{
    RestfulWebhooksWebhooksCtrlBase::deleteOne(req, callback, id);
}

void RestfulWebhooksWebhooksCtrl::get(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulWebhooksWebhooksCtrlBase::get(req, callback);
}

void RestfulWebhooksWebhooksCtrl::create(const HttpRequestPtr &req,
                                         std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulWebhooksWebhooksCtrlBase::create(req, callback);
}

*/
