/**
 *
 *  RestfulRolesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulRolesCtrl.h"
#include <string>




/**
* Uncomment the following methods to customize for business logic.
*/
/*
void RestfulRolesCtrl::getOne(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback,
                              Roles::PrimaryKeyType &&id)
{
    RestfulRolesCtrlBase::getOne(req, callback, id);
}


void RestfulRolesCtrl::updateOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Roles::PrimaryKeyType &&id)
{
    RestfulRolesCtrlBase::updateOne(req, callback, id);
}


void RestfulRolesCtrl::deleteOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Roles::PrimaryKeyType &&id)
{
    RestfulRolesCtrlBase::deleteOne(req, callback, id);
}

void RestfulRolesCtrl::get(const HttpRequestPtr &req,
                           std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulRolesCtrlBase::get(req, callback);
}

void RestfulRolesCtrl::create(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulRolesCtrlBase::create(req, callback);
}

*/
