/**
 *
 *  RestfulWebhooksEventsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulWebhooksEventsCtrlBase.h"

#include "WebhooksEvents.h"
using namespace drogon;

using namespace drogon_model::openproject6;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the webhooks_events table.
 */

class RestfulWebhooksEventsCtrl: public drogon::HttpController<RestfulWebhooksEventsCtrl>, public RestfulWebhooksEventsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulWebhooksEventsCtrl::getOne,"/webhooksevents/{1}",Get,Options);
    ADD_METHOD_TO(RestfulWebhooksEventsCtrl::updateOne,"/webhooksevents/{1}",Put,Options);
    ADD_METHOD_TO(RestfulWebhooksEventsCtrl::deleteOne,"/webhooksevents/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulWebhooksEventsCtrl::get,"/webhooksevents",Get,Options);
    ADD_METHOD_TO(RestfulWebhooksEventsCtrl::create,"/webhooksevents",Post,Options);
    //ADD_METHOD_TO(RestfulWebhooksEventsCtrl::update,"/webhooksevents",Put,Options);
    METHOD_LIST_END
    
    /**
     * Uncomment the following methods to customize for business logic.
     */
     /*
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                WebhooksEvents::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   WebhooksEvents::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   WebhooksEvents::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback);
    */
};
