/**
 *
 *  RestfulOauthAccessGrantsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulOauthAccessGrantsCtrl.h"
#include <string>




/**
* Uncomment the following methods to customize for business logic.
*/
/*
void RestfulOauthAccessGrantsCtrl::getOne(const HttpRequestPtr &req,
                                          std::function<void(const HttpResponsePtr &)> &&callback,
                                          OauthAccessGrants::PrimaryKeyType &&id)
{
    RestfulOauthAccessGrantsCtrlBase::getOne(req, callback, id);
}


void RestfulOauthAccessGrantsCtrl::updateOne(const HttpRequestPtr &req,
                                             std::function<void(const HttpResponsePtr &)> &&callback,
                                             OauthAccessGrants::PrimaryKeyType &&id)
{
    RestfulOauthAccessGrantsCtrlBase::updateOne(req, callback, id);
}


void RestfulOauthAccessGrantsCtrl::deleteOne(const HttpRequestPtr &req,
                                             std::function<void(const HttpResponsePtr &)> &&callback,
                                             OauthAccessGrants::PrimaryKeyType &&id)
{
    RestfulOauthAccessGrantsCtrlBase::deleteOne(req, callback, id);
}

void RestfulOauthAccessGrantsCtrl::get(const HttpRequestPtr &req,
                                       std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulOauthAccessGrantsCtrlBase::get(req, callback);
}

void RestfulOauthAccessGrantsCtrl::create(const HttpRequestPtr &req,
                                          std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulOauthAccessGrantsCtrlBase::create(req, callback);
}

*/
