/**
 *
 *  RestfulWebhooksProjectsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulWebhooksProjectsCtrl.h"
#include <string>




/**
* Uncomment the following methods to customize for business logic.
*/
/*
void RestfulWebhooksProjectsCtrl::getOne(const HttpRequestPtr &req,
                                         std::function<void(const HttpResponsePtr &)> &&callback,
                                         WebhooksProjects::PrimaryKeyType &&id)
{
    RestfulWebhooksProjectsCtrlBase::getOne(req, callback, id);
}


void RestfulWebhooksProjectsCtrl::updateOne(const HttpRequestPtr &req,
                                            std::function<void(const HttpResponsePtr &)> &&callback,
                                            WebhooksProjects::PrimaryKeyType &&id)
{
    RestfulWebhooksProjectsCtrlBase::updateOne(req, callback, id);
}


void RestfulWebhooksProjectsCtrl::deleteOne(const HttpRequestPtr &req,
                                            std::function<void(const HttpResponsePtr &)> &&callback,
                                            WebhooksProjects::PrimaryKeyType &&id)
{
    RestfulWebhooksProjectsCtrlBase::deleteOne(req, callback, id);
}

void RestfulWebhooksProjectsCtrl::get(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulWebhooksProjectsCtrlBase::get(req, callback);
}

void RestfulWebhooksProjectsCtrl::create(const HttpRequestPtr &req,
                                         std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulWebhooksProjectsCtrlBase::create(req, callback);
}

*/
