/**
 *
 *  RestfulCostObjectsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulCostObjectsCtrlBase.h"

#include "CostObjects.h"
using namespace drogon;

using namespace drogon_model::openproject6;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the cost_objects table.
 */

class RestfulCostObjectsCtrl: public drogon::HttpController<RestfulCostObjectsCtrl>, public RestfulCostObjectsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulCostObjectsCtrl::getOne,"/costobjects/{1}",Get,Options);
    ADD_METHOD_TO(RestfulCostObjectsCtrl::updateOne,"/costobjects/{1}",Put,Options);
    ADD_METHOD_TO(RestfulCostObjectsCtrl::deleteOne,"/costobjects/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulCostObjectsCtrl::get,"/costobjects",Get,Options);
    ADD_METHOD_TO(RestfulCostObjectsCtrl::create,"/costobjects",Post,Options);
    //ADD_METHOD_TO(RestfulCostObjectsCtrl::update,"/costobjects",Put,Options);
    METHOD_LIST_END
    
    /**
     * Uncomment the following methods to customize for business logic.
     */
     /*
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                CostObjects::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   CostObjects::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   CostObjects::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback);
    */
};
