// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: time/admin/user/user/list/proto/admin_user_user_ListRequest.proto

#include "time/admin/user/user/list/proto/admin_user_user_ListRequest.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace timeservice {
class UserListRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<UserListRequest> _instance;
} _UserListRequest_default_instance_;
}  // namespace timeservice
static void InitDefaultsscc_info_UserListRequest_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::timeservice::_UserListRequest_default_instance_;
    new (ptr) ::timeservice::UserListRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::timeservice::UserListRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UserListRequest_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_UserListRequest_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::timeservice::UserListRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::timeservice::UserListRequest, status_),
  PROTOBUF_FIELD_OFFSET(::timeservice::UserListRequest, name_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::timeservice::UserListRequest)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::timeservice::_UserListRequest_default_instance_),
};

const char descriptor_table_protodef_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\nAtime/admin/user/user/list/proto/admin_"
  "user_user_ListRequest.proto\022\013timeservice"
  "\"\177\n\017UserListRequest\0223\n\006status\030\001 \001(\0162#.ti"
  "meservice.UserListRequest.Status\022\014\n\004name"
  "\030\002 \001(\t\")\n\006Status\022\007\n\003ALL\020\000\022\n\n\006ACTIVE\020\001\022\n\n"
  "\006LOCKED\020\002b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto_sccs[1] = {
  &scc_info_UserListRequest_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto_once;
static bool descriptor_table_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto = {
  &descriptor_table_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto_initialized, descriptor_table_protodef_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto, "time/admin/user/user/list/proto/admin_user_user_ListRequest.proto", 217,
  &descriptor_table_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto_once, descriptor_table_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto_sccs, descriptor_table_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto::offsets,
  file_level_metadata_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto, 1, file_level_enum_descriptors_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto, file_level_service_descriptors_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto), true);
namespace timeservice {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* UserListRequest_Status_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto);
  return file_level_enum_descriptors_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto[0];
}
bool UserListRequest_Status_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr UserListRequest_Status UserListRequest::ALL;
constexpr UserListRequest_Status UserListRequest::ACTIVE;
constexpr UserListRequest_Status UserListRequest::LOCKED;
constexpr UserListRequest_Status UserListRequest::Status_MIN;
constexpr UserListRequest_Status UserListRequest::Status_MAX;
constexpr int UserListRequest::Status_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void UserListRequest::InitAsDefaultInstance() {
}
class UserListRequest::_Internal {
 public:
};

UserListRequest::UserListRequest()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:timeservice.UserListRequest)
}
UserListRequest::UserListRequest(const UserListRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  status_ = from.status_;
  // @@protoc_insertion_point(copy_constructor:timeservice.UserListRequest)
}

void UserListRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_UserListRequest_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  status_ = 0;
}

UserListRequest::~UserListRequest() {
  // @@protoc_insertion_point(destructor:timeservice.UserListRequest)
  SharedDtor();
}

void UserListRequest::SharedDtor() {
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void UserListRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UserListRequest& UserListRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_UserListRequest_time_2fadmin_2fuser_2fuser_2flist_2fproto_2fadmin_5fuser_5fuser_5fListRequest_2eproto.base);
  return *internal_default_instance();
}


void UserListRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:timeservice.UserListRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  status_ = 0;
  _internal_metadata_.Clear();
}

const char* UserListRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .timeservice.UserListRequest.Status status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::timeservice::UserListRequest_Status>(val));
        } else goto handle_unusual;
        continue;
      // string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(_internal_mutable_name(), ptr, ctx, "timeservice.UserListRequest.name");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UserListRequest::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:timeservice.UserListRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .timeservice.UserListRequest.Status status = 1;
  if (this->status() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_status(), target);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "timeservice.UserListRequest.name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:timeservice.UserListRequest)
  return target;
}

size_t UserListRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:timeservice.UserListRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // .timeservice.UserListRequest.Status status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_status());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UserListRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:timeservice.UserListRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const UserListRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<UserListRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:timeservice.UserListRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:timeservice.UserListRequest)
    MergeFrom(*source);
  }
}

void UserListRequest::MergeFrom(const UserListRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:timeservice.UserListRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.status() != 0) {
    _internal_set_status(from._internal_status());
  }
}

void UserListRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:timeservice.UserListRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserListRequest::CopyFrom(const UserListRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:timeservice.UserListRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserListRequest::IsInitialized() const {
  return true;
}

void UserListRequest::InternalSwap(UserListRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(status_, other->status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UserListRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace timeservice
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::timeservice::UserListRequest* Arena::CreateMaybeMessage< ::timeservice::UserListRequest >(Arena* arena) {
  return Arena::CreateInternal< ::timeservice::UserListRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
